language: node_js
node_js:
- '6'
env:
  matrix:
  - CXX=g++-4.8
  global:
    #TEST_DB_KEY
    secure: ltKbkSUH96zt6FwMKeVImMvQ/j5mHoapPqQeMUqPvrWzJwuvHVAV3n5UGq+fZAipACbB3Au3Gh7X/IKNz12BzLYl9OeXzrTQbmwolKLcEk5C2d2zH377gcRRM4fjLKVKjATlKWl+Kp3i5hya0VOtAMBI8o6zxm7mlojPLXe4ND8f3GAZer76uUCy6HjoNPkToJP1etgCDgsy4oR/SF6fODCfBlNG19goI8xmofzJ3W3mBtIGggdjgm+MUAiwHHK2Z5xCevoR0GzSZfYSK0OwnMNqAOgp+B3AAJYCX/vreZ7wlE54s347r/TwHLfsJNMUvGjftIPSwUrLmFmtdanPIa1rnWMi2Nhr+LLreTm5/6/QAwrnjzai40LQvAFPiW96+ANBaMM82mNaHlI/pnaCeQU3mAENCJJzUUG3erFsW3AV+aW5krkWiiYh2X0+S7XPgvxbisZ+PpqTSZBFCpr1CQyDXKkw6DQvvzOriFvOZQskWBjooR8dYaDAVgYKs/Qferlm8yDeAW05a/yOnJc57dvlhJL4vCvXVNCX8FnKIzgR7z2wR3T/DHam88KnCu32ZgJzTRtVRqoKGYxIFuYA+WO9OCXUWc8/b+iC2dmlojG3SFbrhzVjVwd+Bf+lyFnV9oNXhBLhKA0KfxqDAqXIunSIzJc9v1kxkqsxTeCNclA=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: required
cache:
  directories:
  - node_modules
install:
- npm i -g npm@latest
- npm install
