language: node_js

node_js:
- '6'

env:
  global:
    - CXX=g++-4.8
  #TEST_DB_KEY:
    - secure: k/TANpgYIcthmdjLZ0KUYcFbH25Ed9Fa4bpanVZ/FpazoDfRCLOHrS0FBQlm+8RnolJf2MIMr9ouIbcfvs6U9G8gTW+T0VRQRH5PXcMVaVNtpyRP9NcfZgSi0IzZp1SlzwW+12y0v6dO11ntWcipfckkoopWdbASVW0PZmCKfromMiz7UHAQadLkgIvrzhGPpRN7rwmqTXPvxi0LCMd3fA1RpqGTwN5TNiRMKUJI9dw+4z7e8FkGx2d0qVY8xQaSGTaQPkKiEEQyCsTV+wadfzuqs/NNM2suYngpBDVOyXxXehdeyhQYZS1sT4SMUtRB54JeUgoHLL+GtvvATn0442njHMgAAfrcIiQVDLBrcIzF5HPiutZKyzqE8P/uFsZqiKpeapps60WFuxK9XEGuwYNSKdYFMh3pzfosjrXrxjlpZYrwFF42vmyhGmPWUl7+lboXBSWAiidfi/xD43lZmuwyFLGdjuqBNR6Ok5Dg7KW8MAfa9fWz0NKzwgArXqjZqmCdz787t+DRsl0DU9HCWxI4eZpMs1o4McmGUAm+f2YkvLOQQv8cybyYkAhs9gZcIPIkGhd4CoI/I3mSNOIHn7YdzxTUOd06qRMH63sIBowyLwU6PXjV7G11MCXT5frCEAe2+FIkfVVdqjH47XiVpL0JgOJdncgVlQoR7+aHSOY=
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
sudo: required
      
cache:
  directories:
    - node_modules
    
install:
- npm i -g npm@latest
- npm install
