language: node_js
node_js:
- '6'
- '4'
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: vrYarFxjX36fTO8yXHxH4sO+LHHFjHx0aEh4QBaWxuvYmv+blStf0Hg8G4T8nyBRYC+2TnTiNLQq41vzrNN6E8whCHGCxC3s1DhzKoLaA7PfDe8r5eJa62PsFF579chOe+kkg+JjaS5a21p3Lv1xPx0glA1A53GcZCdJqhf15+YU/Dxn3qodD/6qn8ybV3+TWl9a84MQ6BL3sWalKztaFKMmfhT/XuGbC27XHHqKNgtgyEiUI7SYyNJIbhCKOFUByeUH2DDZkk7+1qug9OonZgzKLZ3j7sbW3g/7BOpTrzSShJLupSAcefHINGV+KX+8QzVb/V/xmqSvKTo6dHibYY+fCo/7gdLytZNzR9UDfQ3ijzhA+n5JaKFFXmBtJ8EK+xFG+x8jv0xf/80l7KmtrOmgoV+FkAh9FuDHZXklIXHxDNzvhk3mwpfPAfkURjpnk5mY9zOccOqcXY+BJgbRnWspf59XdIVwPpeC4dpAt/nsLlNizM/03teaD0I8X+c07DmcQ8R5DW8jZ2ZK57i1RN2RsN+6GW6Ajcj5SgnxSkMQAQRuV8nec9DWdcMSYKArVA1JLbAdZquRpEteJm1xBDeXji0y9XDYUOk7OLgcrFH7oolE1u681YezGGpbX0ZmFg60eYypr3Ilcyv0qCw1qmzZ0ESrOIKosaKs/H86bo4=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: required
cache:
  directories:
  - node_modules
install:
- npm i -g npm@latest
- npm install
