language: node_js

node_js:
- '6'
- '4'

env:
  global:
    - CXX=g++-4.8
  #TEST_DB:
    - secure: uvJ6giumSjIddmySa5cFHNCrA2Q/JrhFlzEcaRfDIvF1YepWt0zleYDaB5ApvcjrxgHkv1WCiIwbfNMDaBTMfZJYRg505Lo4cDKM/lw3f26ljv3KfE4EdLB8tZLfcYpAXc6QdE+EO0jujpl+LWvNSbZvmd2rqgmxCr3dWQcNtO9Yickddnz7gFdIMpqdYdn5MZXjj/CBfOSyqGMQ9gTW1A7dykkcBssJxi/5DnDmql2+KCgGam2IwXH1eIBVDF/3Ns4H5gagG4DYmj7vD0S+WNzLNK4Xj4vL9q2cOxrGoKBPfy6SYpz+JJXKEnL0r2Y05s2Na/kn1oDoSLL7QghHQJN2221N3nQyqO/41E6LnxAqy7piyBq1el6vWg5RWR0gnmrC/O5dxlKK2rZbhBrZmHD05cUYi0nYUDDXJvppEqTTL8KfBEvne/EXI/i9aE8BURmd5GNkM1b2s1znXC40kGy+aCtEaHCpC2PN3BaB7DU8euWlBjhfS6BxtZ+lZNcFT2QWTdaS+syZpzQTpl9yPVLNmXeMN3fkfciauRWLCXY2hUqurJQn65pINcEgUwSWmH0UNzYMwJCEEw7dAwuXN9l7r/Z61joTAXWV/IlBY8UB3JCcTFuLKiSbxoRLoExACLR+8remgOGWLisbnaBVnAfroEjaKpyf0J+MsK4TDUI=
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
sudo: required
      
cache:
  directories:
    - node_modules
    
install:
- npm i -g npm@latest
- npm install
