// Login
export const EMAIL_ADDRESS_INPUT = 'EMAIL_ADDRESS_INPUT';
export const PASSWORD_INPUT = 'PASSWORD_INPUT';
export const EMPTY_LOGIN_FIELD = 'EMPTY_LOGIN_FIELD';
export const FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

